import '../models/financial_entry.dart';
import '../models/financial_month.dart';

FinancialMonth buildInitialFinancialMonth() {
  return FinancialMonth(
    year: 2026,
    month: 8,
    entries: const [
      FinancialEntry(
        id: 'previous-balance',
        name: 'Resto do mês passado',
        amountInCents: 193036,
        type: FinancialEntryType.previousBalance,
      ),
      FinancialEntry(
        id: 'card-picpay',
        name: 'PicPay',
        amountInCents: 96584,
        type: FinancialEntryType.cardInvoice,
        isRecurring: true,
        relatedCardId: '1',
        closingDay: 3,
        dueDay: 10,
      ),
      FinancialEntry(
        id: 'card-nubank',
        name: 'Nubank',
        amountInCents: 147022,
        type: FinancialEntryType.cardInvoice,
        isRecurring: true,
        relatedCardId: '2',
        closingDay: 3,
        dueDay: 10,
      ),
      FinancialEntry(
        id: 'card-assai',
        name: 'Assaí',
        amountInCents: 74692,
        type: FinancialEntryType.cardInvoice,
        isRecurring: true,
        relatedCardId: '3',
        closingDay: 3,
        dueDay: 10,
      ),
      FinancialEntry(
        id: 'card-c6',
        name: 'C6',
        amountInCents: 40645,
        type: FinancialEntryType.cardInvoice,
        isRecurring: true,
        relatedCardId: '4',
        closingDay: 4,
        dueDay: 10,
      ),
      FinancialEntry(
        id: 'card-mercado-pago',
        name: 'Mercado Pago',
        amountInCents: 28492,
        type: FinancialEntryType.cardInvoice,
        isRecurring: true,
        relatedCardId: '5',
        closingDay: 6,
        dueDay: 10,
      ),
      FinancialEntry(
        id: 'card-midway',
        name: 'Riachuelo Midway',
        amountInCents: 5099,
        type: FinancialEntryType.cardInvoice,
        isRecurring: true,
        relatedCardId: '6',
        closingDay: 7,
        dueDay: 13,
      ),
      FinancialEntry(
        id: 'card-neon',
        name: 'Neon',
        amountInCents: 0,
        type: FinancialEntryType.cardInvoice,
        isRecurring: true,
        relatedCardId: '7',
        closingDay: 11,
        dueDay: 15,
      ),
      FinancialEntry(
        id: 'card-next',
        name: 'Next',
        amountInCents: 0,
        type: FinancialEntryType.cardInvoice,
        isRecurring: true,
        relatedCardId: '8',
        closingDay: 18,
        dueDay: 28,
      ),
      FinancialEntry(
        id: 'expense-alicia-analice',
        name: 'Alícia/Analice',
        amountInCents: 100000,
        type: FinancialEntryType.expense,
      ),
      FinancialEntry(
        id: 'expense-brisanet',
        name: 'Brisanet',
        amountInCents: 10990,
        type: FinancialEntryType.expense,
        isRecurring: true,
        dueDay: 10,
      ),
      FinancialEntry(
        id: 'expense-energisa',
        name: 'Energisa',
        amountInCents: 37603,
        type: FinancialEntryType.expense,
        isRecurring: true,
        dueDay: 12,
      ),
      FinancialEntry(
        id: 'expense-caixa-loan',
        name: 'Caixa Empréstimo',
        amountInCents: 22000,
        type: FinancialEntryType.expense,
        isRecurring: true,
        dueDay: 20,
      ),
      FinancialEntry(
        id: 'expense-unimed',
        name: 'Unimed',
        amountInCents: 10000,
        type: FinancialEntryType.expense,
        isRecurring: true,
        dueDay: 20,
      ),
      FinancialEntry(
        id: 'expense-tomography',
        name: 'Tomografia Alícia',
        amountInCents: 2800,
        type: FinancialEntryType.expense,
      ),
      FinancialEntry(
        id: 'income-salary',
        name: 'Salário',
        amountInCents: 205147,
        type: FinancialEntryType.income,
        isRecurring: true,
      ),
      FinancialEntry(
        id: 'income-cost-help',
        name: 'Ajuda de Custo',
        amountInCents: 70000,
        type: FinancialEntryType.income,
        isRecurring: true,
      ),
      FinancialEntry(
        id: 'income-cash',
        name: 'Dinheiro Vivo',
        amountInCents: 10000,
        type: FinancialEntryType.income,
      ),
      FinancialEntry(
        id: 'income-sil-phone-screen',
        name: 'Sil Tela Cel',
        amountInCents: 3659,
        type: FinancialEntryType.income,
      ),
      FinancialEntry(
        id: 'income-cable-locator',
        name: 'InforMais Localizador de Cabos',
        amountInCents: 5715,
        type: FinancialEntryType.income,
      ),
    ],
  );
}
